version: '3'

services:
    postgres:
        image: 'postgres:15'
        container_name: 'java-postgres'
        ports:
            - "5431:5432"
        environment:
            POSTGRES_DB: "db"
            POSTGRES_USER: "user"
            POSTGRES_PASSWORD: "password"